config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  resources :posts do
    resources :comments, only: [ :create, :destroy ]
  end

  devise_for :users

  resources :file_uploads, only: [ :new, :create ]

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post

  scope :most_recent, -> { order(created_at: :desc) }

  validates :body, presence: true
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  has_one_attached :file

  validates :file, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :body
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  scope :most_recent, -> { order(created_at: :desc) }

  validates :title, presence: true
  validates :body, presence: true
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern

  def set_locale
    cookies[:locale] = params[:locale] if params[:locale]

    if cookies[:locale] && I18n.locale != cookies[:locale]
      I18n.locale = cookies[:locale]
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :nickname ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :nickname ])
  end

  private

  def verify_permission
    if current_user != resource_user
      redirect_to root_path, alert: t("text.permission_denied")
    end
  end

  def resource_user
    raise NotImplementedError, t("text.define_resource_alert")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[ create destroy ]
  before_action :set_comment, only: %i[ destroy ]
  before_action :authenticate_user!, only: %i[ destroy ]
  before_action :verify_permission, only: %i[ destroy ]

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user if user_signed_in?

    if @comment.save
      flash[:notice] = t("text.save_success")
      redirect_to post_path(@post)
    else
      flash[:alert] = @comment.errors.full_messages.join(" - ")
      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = t("text.delete_success")
    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def resource_user
    @comment.user
  end
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  def new
    @file_upload = FileUpload.new
  end

  def create
    @file_upload = FileUpload.new(file_upload_params)

    if @file_upload.save
      ProcessFileJob.perform_now(@file_upload)
      redirect_to root_path, notice: t("text.job_schedule")
    else
      render :new, alert: t("text.job_failed")
    end
  end

  private

  def file_upload_params
    params.require(:file_upload).permit(:file, :operation)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :verify_permission, only: %i[ edit update destroy ]

  def index
    if params[:tag].present?
      query = Post.most_recent
                  .includes(:tags)
                  .joins(:tags)
                  .where(tags: { name: params[:tag] })

      @pagy, @posts = pagy(query, items: 3)
    else
      @pagy, @posts = pagy(Post.most_recent, items: 3)
    end
  end

  def show
    @comments = @post.comments.most_recent
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: t("text.post_created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: t("text.post_updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!

    redirect_to root_path, status: :see_other, notice: t("text.post_deleted")
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, tag_ids: [])
  end

  def resource_user
    @post.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def avatar_url(user, size: 200)
    hash = Digest::MD5.hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{hash}.png?s=#{size}"
  end

  def user_avatar(user)
    return avatar_url(user) if user.present?

    asset_path("mask.svg")
  end

  def user_nick(user)
    user&.nickname || "Anon"
  end

  def author_of?(resource)
    user_signed_in? && current_user.id == resource.user_id
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_sidebar_layout.html.erb
<div class="sidebar-layout">
  <header id="header" class="items-center justify-between">
    <%= render "shared/mobile_menu" %>
    <%= link_to "Simple Blog", root_path, class: 'text-3xl text-xl--responsive' %>
    <%= link_to t('button.create_post'), new_post_path, class: 'btn btn--blue btn-lg ', style: "margin-right: 10%" if user_signed_in? %>
  </header>

  <aside id="sidebar">
    <div class="flex flex-col items-center">
      <% if user_signed_in? %>
        <div class="avatar avatar-lg mbe-2">
          <%= image_tag avatar_url(current_user) %>
        </div>
        <span class="font-medium mbe-2"><%= current_user.nickname %></span>

        <div class="relative" data-controller="popover" data-popover-flip-class="popover--flip">
          <button id="menu_button" class="btn btn--blue btn-wide btn-lg mbe-2" data-popover-target="button" data-action="popover#toggle" aria-haspopup="menu" aria-controls="menu">
            <%= t('text.settings') %>
          </button>
          <dialog class="popover" style="--popover-size: 12.5rem; margin-top: -2px" data-controller="menu" data-popover-target="menu" data-action="click@document->popover#closeOnClickOutside keydown.esc->popover#close close->menu#reset keydown.up->menu#prev keydown.down->menu#next">
            <div id="menu" class="menu" role="menu" aria-labelledby="menu_button">
              <div class="menu__header text-2xl"><%= t('text.account') %></div>
              <hr class="menu__separator" role="separator"/>
              <div class="menu__group" role="group">
                <%= link_to t('text.edit_profile'), edit_user_registration_path, class: 'btn menu__item', role: "menuitem" %>
                <%= link_to t('button.logout'), destroy_user_session_path, class: 'btn menu__item', data: { turbo_method: :delete }, role: "menuitem" %>
              </div>
            </div>
            <div id="menu" class="menu" role="menu" aria-labelledby="menu_button">
              <div class="menu__header text-2xl"><%= t('text.language') %></div>
              <hr class="menu__separator" role="separator"/>
              <div class="menu__group" role="group">
                <%= link_to "Português", "#{request.path}?locale=pt-BR", class: 'btn menu__item', role: "menuitem" %>
                <%= link_to "English", "#{request.path}?locale=en", class: 'btn menu__item', role: "menuitem" %>
              </div>
            </div>
          </dialog>
        </div>
        <%= link_to t('button.upload_txt'), new_file_upload_path, class: 'btn btn--positive btn-lg btn-wide mbe-2' %>
      <% else %>
        <%= link_to t('button.login'), new_user_session_path, class: 'btn btn--blue btn-lg btn-wide mbe-5' %>
        <%= link_to t('button.sign_up'), new_user_registration_path, class: 'btn btn--primary btn-lg btn-wide mbe-5' %>
      <% end %>
      <%= yield :primary_content %>
    </div>
  </aside>

  <main id="main">
    <%= yield :secondary_content %>
  </main>
</div>

app/views/comments/_comment.html.erb
<div class="card mbe-2">
  <div class="flex items-center justify-between">
    <div class="flex items-center gap-1">
      <div class="avatar" style="margin-right: 10px;">
        <%= image_tag user_avatar(comment.user), alt: "CN" %>
      </div>
      <div class="flex flex-col">
        <span class="text-sm"><%= user_nick(comment.user) %></span>
        <span class="text-sm text-subtle"><%= time_ago_in_words(comment.created_at) %> <%= t("text.ago") %></span>
      </div>
    </div>
    <% if author_of?(comment) %>
      <%= button_to t("button.delete"), post_comment_path(comment.post, comment), 
                                        method: :delete, 
                                        data: { turbo_confirm: t("text.are_you_sure") }, 
                                        class: "btn btn--negative" %>
    <% end %>
  </div>
  <div>
    <p class="text-sm"><%= comment.body %></p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [post, post.comments.build], class: 'mt-2') do |form| %>
  <div>
    <%= form.text_area :body, required: true, class: 'input', placeholder: t('text.leave_a_comment') %>
  </div>

  <div>
    <%= form.submit t('button.submit'), class: 'btn btn btn--primary mbe-2' %>
  </div>
<% end %>

app/views/file_uploads/new.html.erb
<% content_for :primary_content do %>
  <%= link_to t('text.back_to_posts'), root_path, class: 'btn btn--primary btn-wide btn-lg' %>
<% end %>
<% content_for :secondary_content do %>
  <div class="flex justify-center items-center">
    <%= form_with(model: @file_upload, local: true, html: { class: 'card flex flex-col gap' }) do |form| %>
      <div class="field flex flex-col gap-half">
        <%= form.label :file, class: 'text-sm font-medium leading-none' %>
        <%= form.file_field :file, class: 'input' %>
        <p class="text-xs text-subtle mt-1"><%= t('text.tag_tip') %></p>
      </div>

      <div class="actions flex items-center mb-2">
        <%= form.submit t('button.submit'), class: 'btn btn--primary i-full' %>
      </div>
    <% end %>
  </div>
<% end %>

 <%= render 'sidebar_layout' %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Simple Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <script src="https://unpkg.com/slim-select@latest/dist/slimselect.min.js"></script>
    <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet"></link>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flash_msg" if flash.present? %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Simple Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="header-layout">
      <header id="header">
        <div><%= link_to 'Simple Blog', root_path, class: 'text-3xl' %></div>
      </header> 
    <div class="centered-layout bg-shade">
      <%= render "shared/flash_msg" if flash.present? %>
      <main class="card">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, html: { contents: true }) do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert--negative flex flex-col gap-half mbe-4" role="alert">
      <h2 class="font-medium leading-none"><%= t('errors.template.body') %></h2>

      <ul class="text-sm mis-3" style="list-style: disc"> 
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col gap-half mbe-4">
    <%= form.label t('text.title'), class: "text-sm font-medium leading-none" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="flex flex-col gap-half mbe-4">
    <%= form.label :tag_ids, "Tags" %>
    <%= form.collection_select :tag_ids, Tag.all, :id, :name, {}, { multiple: true, data: {controller: "slim", placeholder: t('text.select_value'), search: t('text.search') } }  %>
  </div>

  <div class="flex flex-col gap-half mbe-4">
    <%= form.label t('text.message'), class: "text-sm font-medium leading-none" %>
    <%= form.rich_text_area :body, class: "input" %>
  </div>

  <div class="inline-flex items-center mbs-2 mie-1">
    <%= form.submit class: "btn btn--primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="prose container">
  <div class="flex items-center justify-between">
    <h1><%= post.title %></h1>
    <% if author_of?(post) %>
      <div class="flex items-center gap-half">
        <%= link_to t('button.edit'), edit_post_path(post), class: 'btn btn-lg', style: 'text-decoration: none;' %>
        <%= link_to t('button.delete'), post_path(post), 
                                        data: { turbo_method: :delete, 
                                        turbo_confirm: t('text.are_you_sure') }, 
                                        class: 'btn btn--negative btn-lg', 
                                        style: 'text-decoration: none;' %>
      </div>
    <% end %>
  </div>
  <div class="flex items-center gap-1">
    <div class="avatar" style="margin-right: 10px;">
      <%= image_tag avatar_url(post.user), alt: "CN" %>
    </div>
    <div class="flex flex-col">
      <span class="text-sm"><%= post.user.nickname %></span>
      <span class="text-sm text-subtle"><%= time_ago_in_words(post.created_at) %> <%= t('text.ago') %></span>
    </div>
  </div>
  <p><%= post.body %></p>

  <% comments.each do |comment| %>
    <%= render 'comments/comment', post: post, comment: comment %>
  <% end %>
  <%= render 'comments/form', post: @post %>

  <p><%= link_to t('button.back'), posts_path %></p>
</div>

app/views/posts/edit.html.erb
<% content_for :title, t('button.edit') %>

<% content_for :primary_content do %>
  <%= link_to t('text.back_to_posts'), posts_path, class: 'btn btn--primary btn-lg btn-wide' %>
<% end %>

<% content_for :secondary_content do %>
  <h1 class="font-bold text-4xl mbe-4">Editing post</h1>
  <%= render "form", post: @post %>

  <div class="inline-flex flex-wrap items-center gap mbs-2" style="--row-gap: .5rem">
    <%= link_to t('button.show_post'), @post, class: "btn" %>
    <%= link_to t('text.back_to_posts'), posts_path, class: "btn" %>
  </div>
<% end %>

<%= render "sidebar_layout" %>  

app/views/posts/index.html.erb
<% content_for :title, "Posts" %>

<% content_for :secondary_content do %>

  <%= form_with(url: posts_path, method: :get, html: { class: 'flex justify-end items-center gap-2' }) do %>
    <%= select_tag 'tag', options_from_collection_for_select(Tag.all, 'name', 'name', params[:tag]), 
                                                              prompt: t('text.select_tag'), 
                                                              class: 'input',
                                                              style: "inline-size: 15%; margin-right: 4px;" %>
    <%= submit_tag t('button.filter'), class: 'btn btn--primary' %>
  <% end %>

  <div id="posts" class="flex flex-col" style="gap: 2rem;">
    <% @posts.each do |post| %>
      <div class="flex flex-col items-start gap">
        <div class="card flex flex-col gap-half bg-card" style="width: 100%;" >
          <div class="flex gap items-center justify-between">
            <div class="flex gap items-center">
              <div class="avatar">
                <%= image_tag avatar_url(post.user), alt: "CN" %>
              </div>
              <div class="flex flex-col">
                <span class="font-medium leading-none"><%= post.user.nickname %></span>
                <span class="text-subtle"><%= time_ago_in_words(post.created_at) %> <%= t('text.ago') %></span>
              </div>
            </div>
            <div class="flex gap">
              <% post.tags.each do |tag| %>
                <span class="badge badge--primary"><%= tag.name %></span>
              <% end %>
            </div>
          </div>
        
          <%= link_to post do %> 
            <div class="card flex flex-col gap-half bg-card">
              <span class="text-3xl font-medium leading-none"><%= post.title %></span>
              <p class="leading-none text-subtle text-sm"><%= truncate(post.body.to_plain_text, length: 400) %></p>
            </div>
          <% end %>
          <div class="flex items-center gap-half" style="margin-left: 1px;">
            <%= image_tag 'comment.svg', alt: 'Comments', class: 'icon' %>
            <span><%= post.comments.size %></span>
          </div>
        </div>
      </div>
    <% end %>
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  </div>
<% end %>

<%= render "sidebar_layout" %>

app/views/posts/new.html.erb
<% content_for :title, t('button.create_post') %>

<% content_for :primary_content do %>
  <div class="inline-flex flex-wrap items-center gap" style="--row-gap: .5rem">
    <%= link_to t('text.back_to_posts'), posts_path, class: "btn btn--primary btn-lg btn-wide " %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <h1 class="font-bold text-4xl mbe-4"><%= t('button.create_post') %></h1>
  <%= render "form", post: @post %>
<% end %>

<%= render "sidebar_layout" %>

app/views/posts/show.html.erb
<% content_for :primary_content do %>
  <%= link_to t('text.back_to_posts'), root_path, class: 'btn btn--primary btn-lg btn-wide' %>
<% end %>

<% content_for :secondary_content do %>
  <%= render partial: 'post', locals: { post: @post, comments: @comments } %>
<% end %>

<%= render 'sidebar_layout' %>

app/views/shared/_flash_msg.html.erb
<% flash.each do |type, msg|%>
  <div popover class="flash" style="--flash-position: 1rem;" data-controller="element-removal" data-action="animationend->element-removal#remove" role="alert">
    <%= image_tag "circle-alert.svg", class: "colorize-negative", size: 20, aria: { hidden: true } if type == 'alert' %>
    <%= tag.span msg %>
  </div>
<% end %>

app/views/shared/_mobile_menu.html.erb
<div class="hide@md" data-controller="dialog">
  <button class="btn btn--icon" data-action="dialog#showModal">
    <%= image_tag "menu.svg", size: 20, aria: { hidden: true } %>
    <span class="sr-only">Open menu</span>
  </button>

  <dialog class="sheet sheet--left" data-dialog-target="menu" data-action="click->dialog#closeOnClickOutside">
    <button class="btn btn--plain sheet__close" data-action="click->dialog#close">
      <%= image_tag "x.svg", size: 16, aria: { hidden: true } %>
      <span class="sr-only">Close</span>
    </button>
    <div class="sheet__content">
      <div class="flex flex-col items-center gap-half" style="margin-top: 2rem;">
        <% if user_signed_in? %>
          <%= link_to t('button.logout'), destroy_user_session_path, class: 'btn btn-wide btn-lg btn--primary', data: { turbo_method: :delete } %>
        <% else %>
          <%= link_to t('button.login'), new_user_session_path, class: "btn btn-wide btn-lg btn--primary" %>
          <%= link_to t('button.sign_up'), new_user_registration_path, class: "btn btn--secondary btn-lg btn-wide"%>
        <% end %>
        <%= link_to "Português", "#{request.path}?locale=pt-BR", class: 'btn btn--positive btn-lg btn-wide' %>
        <%= link_to "English", "#{request.path}?locale=en", class: 'btn btn--blue btn-lg btn-wide' %>
      </div>
    </div>
  </dialog>
</div>